InnoNet.WebApi/Models/Reply/DeleteReplyModel.cs
namespace InnoNet.WebApi.Models.Reply
{
    public class DeleteReplyModel
    {
        public int Id { get; set; }
        public string AuthorName { get; set; }
        public string Content { get; set; }
        public int PostId { get; set; }
        public string PostTitle { get; set; }
    }
}

InnoNet.WebApi/Models/Reply/EditPostReplyModel.cs
namespace InnoNet.WebApi.Models.Reply;

public class EditPostReplyModel
{
    public int PostId { get; set; }
    public string PostTitle { get; set; }
    public int ReplyId { get; set; }
    public string AuthorName { get; set; }
    public string Content { get; set; }

}

InnoNet.WebApi/Models/Reply/PostReplyModel.cs
namespace InnoNet.WebApi.Models.Reply;

public class PostReplyModel
{
    public int Id { get; set; }
    public string AuthorId { get; set; }
    public string AuthorName { get; set; }
    public int AuthorRating { get; set; }
    public string AuthorImageUrl { get; set; }
    public bool IsAuthorAdmin { get; set; }
    public DateTime Created { get; set; }
    public string ReplyContent { get; set; }
    public int PostId { get; set; }
    public string PostTitle { get; set; }
    public string PostContent { get; set; }
    public int ForumId { get; set; }
    public string ForumName { get; set; }
    public string ForumImageUrl { get; set; }
}

InnoNet.WebApi/Controllers/ReplyController.cs
using InnoNet.Data.Entities;
using InnoNet.Data.Services;
using InnoNet.WebApi.Models.Reply;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace InnoNet.WebApi.Controllers;

[Authorize]
public class ReplyController : Controller
{
    private readonly IPost _postService;
    private readonly IPostReply _replyService;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IApplicationUser _userService;

    public ReplyController(IPost postService, IApplicationUser userService, IPostReply replyService,
        UserManager<ApplicationUser> userManager)
    {
        _replyService = replyService;
        _postService = postService;
        _userService = userService;
        _userManager = userManager;
    }

    public async Task<ActionResult> Create(int id)
    {
        var post = await _postService.GetById(id);
        if (post == null) return RedirectToAction("Error", "Home");
        var user = await _userManager.FindByNameAsync(User.Identity?.Name);
        var model = new PostReplyModel
        {
            PostId = post.Id,
            PostContent = post.Content,
            PostTitle = post.Title,
            AuthorId = user.Id,
            AuthorName = User.Identity.Name,
            AuthorImageUrl = user.ProfileImageUrl,
            IsAuthorAdmin = User.IsInRole("Admin"),
            ForumId = post.Forum.Id,
            ForumName = post.Forum.Title,
            ForumImageUrl = post.Forum.ImageUrl,
            Created = DateTime.Now
        };
        return View(model);
    }

    [HttpPost]
    [Authorize]
    public async Task<ActionResult> CreateReply(PostReplyModel model)
    {
        var userId = _userManager.GetUserId(User);
        var user = await _userManager.FindByIdAsync(userId);
        var reply = await BuildReply(model, user);
        await _postService.AddReply(reply);
        await _userService.UpdateUserRating(userId, typeof(PostReply));
        return RedirectToAction("Index", "Post", new { id = model.PostId });
    }

    [Authorize]
    public async Task<IActionResult> Edit(int id)
    {
        var reply = await _replyService.GetById(id);
        if (reply == null) return RedirectToAction("Error", "Home");
        var model = new EditPostReplyModel
        {
            PostId = reply.Post.Id,
            ReplyId = reply.Id,
            AuthorName = reply.User.UserName,
            Content = reply.Content,
            PostTitle = reply.Post.Title
        };
        return View(model);
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> EditReply(EditPostReplyModel model)
    {
        var existingReply = await _replyService.GetById(model.ReplyId);

        if (existingReply == null)
        {
            // Handle the case where the reply is not found
            return RedirectToAction("Error", "Home");
        }

        // Check if the current user has the right permissions to edit the reply
        if (!User.IsInRole("Admin") && existingReply.User.UserName != User.Identity.Name)
        {
            // Handle unauthorized access
            return RedirectToAction("Error", "Home");
        }

        // Update the reply content
        existingReply.Content = model.Content;

        // Save the changes
        await _replyService.Edit(existingReply);

        return RedirectToAction("Index", "Post", new { id = model.PostId });
    }

    [Authorize]
    public async Task<IActionResult> Delete(int id)
    {
        var reply = await _replyService.GetById(id);
        if (reply == null)
            return RedirectToAction("Error", "Home");

        var model = new DeleteReplyModel
        {
            Id = reply.Id,
            AuthorName = reply.User?.UserName ?? "ForumAdmin",
            Content = reply.Content,
            PostId = reply.Post?.Id ?? 0,
            PostTitle = reply.Post.Title
        };

        return View(model);
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> ConfirmDelete(int id)
    {
        var reply = await _replyService.GetById(id);

        if (reply == null)
            return RedirectToAction("Error", "Home"); // or handle the error in another way

        var postId = reply.Post.Id;

        await _replyService.Delete(id);

        return RedirectToAction("Index", "Post", new { id = postId });
    }



    private async Task<PostReply> BuildReply(PostReplyModel model, ApplicationUser user)
    {
        var post = await _postService.GetById(model.PostId);

        return new PostReply
        {
            Post = post,
            Content = model.ReplyContent,
            Created = DateTime.Now,
            User = user
        };
    }
}

InnoNet.WebApi/Views/Reply/Create.cshtml
@model InnoNet.WebApi.Models.Reply.PostReplyModel
@{
    ViewData["Title"] = "Create Reply";
}

<div class="container body-content">
    <div class="container body-content">
        <div class="row sectionHeader">
            <div class="sectionHeading">
                Reply | @Model.PostTitle
                <div class="forumLogo" style="background-image: url(@Model.ForumImageUrl)"></div>
                <span id="headingBtn">
                    <a asp-controller="Post" asp-action="Index" asp-route-id="@Model.PostId" class="btn btn-back">Back to @Model.PostTitle</a>
                </span>
            </div>
        </div>
        <div class="row">
            <div id="originalPost">
                <h3 style="color: black">
                    @Model.PostTitle
                </h3>
                <p style="color: black">
                    @Model.PostContent
                </p>
            </div>
        </div>
        <div class="row">
            <div id="createReply">
                <div class="authorBlock">
                    You are posting a reply as @Model.AuthorName
                </div>
                <form asp-action="CreateReply" method="post" id="addPostForum">
                    <div asp-validation-summary="All" class="text-danger">
                    </div>
                    <div class="form-group">
                        <label asp-for="ReplyContent">Reply: </label>
                        <textarea asp-for="ReplyContent" rows="10" class="form-control" required placeholder="Write your reply..." maxlength="300"></textarea>
                        <span asp-validation-for="ReplyContent" class="text-danger"></span>
                    </div>
                    <button type="submit" id="submitReplyBtn" class="btn btn-submitPost">Submit Reply</button>
                    <input asp-for="AuthorId" type="hidden" />
                    <input asp-for="PostId" type="hidden" />
                    <input asp-for="ForumId" type="hidden" />
                </form>
            </div>
        </div>
    </div>
</div>

InnoNet.WebApi/Views/Reply/Delete.cshtml
@model InnoNet.WebApi.Models.Reply.DeleteReplyModel

<h2>Delete Reply</h2>
<p>Are you sure you want to delete this reply by "@Model.AuthorName"?</p>

<p>
    <strong>Author:</strong> @Model.AuthorName<br />
    <strong>Content:</strong> @Model.Content<br />
    <strong>Post Title:</strong> @Model.PostTitle
</p>

<form asp-action="ConfirmDelete" asp-route-id="@Model.Id" method="post">
    <button type="submit" class="btn btn-danger">Delete</button>
    <a asp-action="Index" asp-controller="Post" asp-route-id="@Model.PostId" class="btn btn-secondary">Cancel</a>
</form>

InnoNet.WebApi/Views/Reply/Edit.cshtml
@model InnoNet.WebApi.Models.Reply.EditPostReplyModel
@{
    ViewData["Title"] = "Edit";
}

<div class="container body-content">
    @if (User.Identity.Name == Model.AuthorName || User.IsInRole("Admin"))
    {
        <div class="container body-content">
            <div class="row sectionHeader">
                <div class="sectionHeading">
                    Edit Message
                    <span id="headingBtn">
                        <a asp-controller="Post" asp-action="Index" asp-route-id="@Model.PostId" class="btn btn-back">Back to @Model.PostTitle</a>
                    </span>
                </div>
            </div>
            <div class="row">
                <div id="editReply">
                    <form asp-controller="Reply" asp-action="EditReply" method="post" id="addPostForum">
                        <div asp-validation-summary="All" class="text-danger">
                        </div>
                        <div class="form-group">
                            <label asp-for="Content">Message: </label>
                            <textarea asp-for="Content" rows="10" class="form-control" required placeholder="Write your reply..." value="@Model.Content" maxlength="300"></textarea>
                            <span asp-validation-for="Content" class="text-danger"></span>
                        </div>
                        <input asp-for="ReplyId" type="hidden" />
                        <input asp-for="PostId" type="hidden" />
                        <button type="submit" id="submitReplyBtn" class="btn btn-submitPost">Submit Reply</button>
                    </form>
                </div>
            </div>
        </div>
    }
    else
    {
        <h1 class="text-danger">Error.</h1>
        <h2 class="text-danger">You do not have access to this profile</h2>
    }
</div>